SELECT
    _FIVETRAN_ID,
    CAST(CLIENT_ID AS STRING) AS CLIENT_ID,
    IP,
    SESSION_ID,
    SESSION_AT AS SESSION_TIME_TS,
    OS,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS

FROM {{ source('web_schema', 'sessions') }}