SELECT
    _FILE,
    _LINE,
    _MODIFIED AS MODIFIED_TS,
    _FIVETRAN_SYNCED AS FIVETRAN_SYNCED_TS,
    CAST(EMPLOYEE_ID AS STRING) AS EMPLOYEE_ID,
    TO_DATE(REPLACE(HIRE_DATE, 'day ', '')) AS HIRE_DATE,
    NAME,
    CITY,
    ADDRESS,
    TITLE,
    ANNUAL_SALARY
FROM {{ source('google_drive', 'hr_joins') }}