SELECT
    _FILE,
    _LINE,
    _MODIFIED AS MODIFIED_TS,
    _FIVETRAN_SYNCED AS FIVETRAN_SYNCED_TS,
    RETURNED_AT AS RETURNED_DATE,
    CAST(ORDER_ID AS STRING) AS ORDER_ID,
    IS_REFUNDED
FROM {{ source('google_drive', 'returns') }}