version: 2

sources:
  - name: google_drive
    database: LOAD
    schema: GOOGLE_DRIVE
    tables: 
      - name: expenses
      - name: returns
      - name: hr_joins
      - name: hr_quits

  - name: web_schema
    database: LOAD
    schema: SNOWFLAKE_DB_WEB_SCHEMA
    tables:
      - name: orders
      - name: sessions
      - name: item_views
      - name: page_views
